// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5aIzxbMlxUj2xVnu30yjn-7K28zDfS4I',
    appId: '1:193333945671:web:3fa3980acf81fa3973d862',
    messagingSenderId: '193333945671',
    projectId: 'bankease-610fb',
    authDomain: 'bankease-610fb.firebaseapp.com',
    storageBucket: 'bankease-610fb.appspot.com',
    measurementId: 'G-B8D3LKJ04C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv_3KekKFEV8pPj92WIebNZ2pGaIoXBGU',
    appId: '1:193333945671:android:124d687b02f0070973d862',
    messagingSenderId: '193333945671',
    projectId: 'bankease-610fb',
    storageBucket: 'bankease-610fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSobri_-yp8791Y4dGfepSS7f6_PCeTyM',
    appId: '1:193333945671:ios:150eb9d61317e7a473d862',
    messagingSenderId: '193333945671',
    projectId: 'bankease-610fb',
    storageBucket: 'bankease-610fb.appspot.com',
    androidClientId: '193333945671-bk1df06d14ub217bpgthiilbubuqm73b.apps.googleusercontent.com',
    iosClientId: '193333945671-2uj0ppppsp0pk82n5lb1svi4lfml456m.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSobri_-yp8791Y4dGfepSS7f6_PCeTyM',
    appId: '1:193333945671:ios:a9fdf17aff7ac58b73d862',
    messagingSenderId: '193333945671',
    projectId: 'bankease-610fb',
    storageBucket: 'bankease-610fb.appspot.com',
    androidClientId: '193333945671-bk1df06d14ub217bpgthiilbubuqm73b.apps.googleusercontent.com',
    iosClientId: '193333945671-09aoqlco1hkmlhnl8r5ijps3gpvttfvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankease.RunnerTests',
  );
}
